import type { Document } from './types';

export const documents: Document[] = [
  {
    id: 'EST-001',
    type: 'Estimate',
    status: 'Sent',
    clientName: 'Acme Corp',
    clientEmail: 'contact@acme.com',
    projectTitle: 'Website Redesign',
    issuedDate: '2024-07-15',
    amount: 5000,
    lineItems: [
      { id: '1', description: 'Phase 1: Discovery & Strategy', quantity: 1, price: 1000 },
      { id: '2', description: 'Phase 2: UI/UX Design', quantity: 1, price: 2500 },
      { id: '3', description: 'Phase 3: Frontend Development', quantity: 1, price: 1500 },
    ],
    notes: 'This estimate is valid for 30 days.',
    terms: '50% upfront, 50% upon completion.',
  },
  {
    id: 'INV-001',
    type: 'Invoice',
    status: 'Paid',
    clientName: 'Innovate LLC',
    clientEmail: 'billing@innovate.com',
    projectTitle: 'Mobile App Development',
    issuedDate: '2024-07-01',
    dueDate: '2024-07-31',
    amount: 12000,
    lineItems: [
      { id: '1', description: 'iOS App Development', quantity: 1, price: 6000 },
      { id: '2', description: 'Android App Development', quantity: 1, price: 6000 },
    ],
    notes: 'Thank you for your business!',
    terms: 'Net 30.',
  },
  {
    id: 'INV-002',
    type: 'Invoice',
    status: 'Partial',
    clientName: 'Synergy Solutions',
    clientEmail: 'accounts@synergy.com',
    projectTitle: 'Cloud Migration',
    issuedDate: '2024-06-20',
    dueDate: '2024-07-20',
    amount: 7500,
    lineItems: [{ id: '1', description: 'Data Migration and Setup', quantity: 1, price: 7500 }],
    notes: 'Partial payment of $3000 received.',
    terms: 'Net 30.',
  },
  {
    id: 'EST-002',
    type: 'Estimate',
    status: 'Draft',
    clientName: 'Quantum Industries',
    clientEmail: 'info@quantum.com',
    projectTitle: 'Logo and Brand Guide',
    issuedDate: '2024-07-18',
    amount: 2500,
    lineItems: [
      { id: '1', description: 'Logo Concepts (3 rounds)', quantity: 1, price: 1500 },
      { id: '2', description: 'Brand Style Guide', quantity: 1, price: 1000 },
    ],
    notes: 'Awaiting final project scope.',
    terms: '50% deposit required to start.',
  },
    {
    id: 'INV-003',
    type: 'Invoice',
    status: 'Overdue',
    clientName: 'Apex Constructors',
    clientEmail: 'billing@apex.com',
    projectTitle: 'Marketing Campaign Q2',
    issuedDate: '2024-05-10',
    dueDate: '2024-06-09',
    amount: 3200,
    lineItems: [
      { id: '1', description: 'Social Media Management', quantity: 1, price: 1200 },
      { id: '2', description: 'Content Creation (4 articles)', quantity: 1, price: 2000 },
    ],
    notes: 'Reminder: This invoice is past due.',
    terms: 'Net 30.',
  },
];
